// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceReservation.Infrastructure.Data;

#nullable disable

namespace ResourceReservation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResourceReservation.Core.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Reservation_User_Status");

                    b.HasIndex("ResourceId", "StartTime", "EndTime", "Status")
                        .HasDatabaseName("IX_Reservation_Resource_Time_Status");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ResourceReservation.Core.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxConcurrentUsage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxConcurrentUsage = 1,
                            Name = "اتاق جلسه A",
                            Type = "اتاق جلسه"
                        },
                        new
                        {
                            Id = 2,
                            MaxConcurrentUsage = 1,
                            Name = "اتاق جلسه B",
                            Type = "اتاق جلسه"
                        },
                        new
                        {
                            Id = 3,
                            MaxConcurrentUsage = 1,
                            Name = "پروژکتور ۱",
                            Type = "پروژکتور"
                        },
                        new
                        {
                            Id = 4,
                            MaxConcurrentUsage = 1,
                            Name = "خودرو شرکتی",
                            Type = "خودرو"
                        });
                });

            modelBuilder.Entity("ResourceReservation.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ali@company.ir",
                            Name = "علی احمدی"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maryam@company.ir",
                            Name = "مریم رضایی"
                        });
                });

            modelBuilder.Entity("ResourceReservation.Core.Entities.Reservation", b =>
                {
                    b.HasOne("ResourceReservation.Core.Entities.Resource", "Resource")
                        .WithMany("Reservations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourceReservation.Core.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResourceReservation.Core.Entities.Resource", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ResourceReservation.Core.Entities.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
